FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# НЕ запускаем скрипт здесь:
# RUN python Ozon.py  <-- убрать!

# Запуск бота при старте контейнера
CMD ["python", "Ozon.py"]
